# Generated by Django 5.2.2 on 2025-08-04 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("borrowings", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="borrowing",
            name="expected_return_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
